### ISSUE TITLE
Getting ERROR

### ISSUE THREAD

**Issue by sekhwal** [jkkbuddika/RNA-Seq-Data-Analyzer#3] opened 2020-07-30 16:25 UTC
Hi, I am getting an error while running final command :  python run.py
Here are my command details::

$ python run.py 
Enter the species code (Options: hs, mm, dm, ce, dr or custom): hs
Enter the Run Mode (Options: 0 for single-end or 1 for paired-end): 1
Deduplication (Options: TRUE or FALSE): TRUE
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    import FeatureCounter
  File "/DataAnalysis/Manoj-data/RNA-data-analyzer/scripts/FeatureCounter.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by jkkbuddika** [comment] 2020-07-30 17:37
Hello, Looks like you have not installed the "pandas" package. Are you using the miniconda environment that I describe in the User Guide? Try installing pandas package and rerun.

If you are using the miniconda environment (dataanalyzer that you create in Step 2) you can do this by running:

conda install -n dataanalyzer -c conda-forge -c bioconda pandas

Let me know if you have any more problems.

**Comment by sekhwal** [comment] 2020-07-30 20:53
Hi, it running. However, it is taking so long time. How I can give my own reference and .gtf file. 

Here is the process showing:

Creating the STAR Reference Genome ...

Jul 30 15:08:35 ..... started STAR run
Jul 30 15:08:35 ... starting to generate Genome files
Jul 30 15:09:26 ..... processing annotations GTF
Jul 30 15:09:54 ... starting to sort Suffix Array. This may take a long time...
Jul 30 15:10:12 ... sorting Suffix Array chunks and saving them to disk...

**Comment by jkkbuddika** [comment] 2020-07-30 21:04
Hey, great! It automatically downloads the latest GENCODE human genome assembly and the GTF (https://www.gencodegenes.org/human/). You don't have to manually specify that! Usually, it takes a long time to get the human genome assembled. Give it some time and see. Also, given you have so many files to analyze I imagine it will take some time to go all the way. Let me know if you run into any issues.

**Comment by sekhwal** [comment] 2020-07-30 21:25
thank you for your help!

I have a couple of questions: 
I have provided all fastq.gz file in a directory called "raw_sequence" in same directory where other pipeline's directories are present such as scripts and environment.
Is the pipeline taking raw sequences automatically while running the pipeline? And how I can provide the reference genome manually. I may have different one.

-----Running command that I followed---
$source activate dataanalyzer
$cd scripts
$python run.py

**Comment by jkkbuddika** [comment] 2020-07-30 22:19
Not a problem. 

Ok, here's the thing. The pipeline requires input sequences in .fastq format inside the "raw_sequence**s**" folder. You can convert all your .fastq.gz files to .fastq by running the following bash command.

`for i in 'ls *.fastq.gz'; do
echo $(gunzip $i)
done`

Also, the individual file names should end with "_R1.fastq" and "_R2.fastq" (See [Step 3](https://github.com/jkkbuddika/RNA-Seq-Data-Analyzer/blob/master/USERGUIDE.md#step-3-input-data-preparation) of the user guide). I have given a bash command that would easily rename everything to the correct format (refer to [Step 3](https://github.com/jkkbuddika/RNA-Seq-Data-Analyzer/blob/master/USERGUIDE.md#step-3-input-data-preparation) again).

When you are ready to run the pipeline, there should be three folders in your home directory: environment, raw_sequences, scripts (looks like you have done that properly).

If you wish to change the sequence and GTF files, you can do that by doing this.

cd scripts
emacs CommonOptions.py

This will open the python script using the emacs text editor. Instead of emacs, you can use any other text editor for this purpose. Scroll down and find support genomes/annotations sections (see the attached image).

<img width="1028" alt="Screen Shot 2020-07-30 at 6 12 51 PM" src="https://user-images.githubusercontent.com/15448916/88979846-79465f00-d290-11ea-8e5f-86473191bf10.png">

You can replace the FTP links under hs_genome or hs_annotation (because you need human data) with FTP links of your preference. Save and exit from emacs (usually ctrl + x + s and then ctrl + x + c).

Then execute the program by running:

source activate dataanalyzer (if you haven't already activated)
python run.py

Hope I have given enough details. This looks like a lot, but easy enough to do. Let me know if you need further assistance.

**Comment by sekhwal** [comment] 2020-07-31 14:56
Hi, the pipeline is on the following process for more than 24hrs. I just want to make sure, is that normal?

Star Alignment Completed!!!
Alignment Quality Assessment Completed!!!
Filtering, Sorting and Indexing Completed!!!
BigWig files were deposited!!!
Feature counting started ...
Quantifying genes ...
Reading data from <STDIN> for featureCounts ...

**Comment by jkkbuddika** [comment] 2020-07-31 15:43
No! It doesn't look correct. Can you please check whether you have the following in your home folder in correct naming organization (see my above comment). The fastq files should be in a folder named "raw_sequences" not "raw_sequence". And the pipeline require .fastq files as raw files, not .fastq.gz (in the above comment I have given an easy bash command to unzip everything at once). Raw file naming is critical: should end with "_R1.fastq" and "_R2.fastq", that's how the program knows it is paired-end and which file represent forward and which one represent reverse. Arrange things in this following order before re-run.

<img width="904" alt="Screen Shot 2020-07-31 at 11 38 01 AM" src="https://user-images.githubusercontent.com/15448916/89051954-ff12ea80-d322-11ea-8b05-07d7ce924077.png">

**Comment by sekhwal** [comment] 2020-07-31 17:19
Hi,
It seems it is completed. However, it is showing some ERROR at the end and I cannot see Featurecount table. Is it mandatory to RUN the pipeline in the Home directory?
I am running it in another directory.

MESSAGE:

Alignment Quality Assessment Completed!!!

Filtering and Sorting: FmaC-218_S8_L001_R1_aligned.bam ...

samtoolssamtools: : error while loading shared librarieserror while loading shared libraries: : libcrypto.so.1.0.0libcrypto.so.1.0.0: : cannot open shared object filecannot open shared object file: : No such file or directoryNo such file or directory

Traceback (most recent call last):
  File "run.py", line 41, in <module>
    ss.sam_sorting()
  File "/DataAnalysis/Manoj-data/pipelines/RNA-data-analyzer/scripts/SamTools.py", line 52, in sam_sorting
    sp.check_call(command, shell=True)
  File "/home/ravibioinfo/miniconda3/envs/dataanalyzer/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'samtools sort -n -@ 8 -T /DataAnalysis/Manoj-data/pipelines/RNA-data-analyzer/sam_sorted/ /DataAnalysis/Manoj-data/pipelines/RNA-data-analyzer/star_aligned/FmaC-218_S8_L001_R1_aligned.bam | samtools view -F 2316 -f 3 -O BAM -@ 8 -o /DataAnalysis/Manoj-data/pipelines/RNA-data-analyzer/sam_sorted/FmaC-218_S8_L001_R1_alignedsorted.bam' returned non-zero exit status 127.

**Comment by jkkbuddika** [comment] 2020-07-31 18:33
Hi, Is it possible for you to share a pair of sequence files with me? May be use google drive or OneDrive? I can take a look.

Did you install samtools in your conda environment? The command looks correct and shouldn't yield any errors.

`samtools sort -n -@ 8 -T /DataAnalysis/Manoj-data/pipelines/RNA-data-analyzer/sam_sorted/ /DataAnalysis/Manoj-data/pipelines/RNA-data-analyzer/star_aligned/FmaC-218_S8_L001_R1_aligned.bam | samtools view -F 2316 -f 3 -O BAM -@ 8 -o /DataAnalysis/Manoj-data/pipelines/RNA-data-analyzer/sam_sorted/FmaC-218_S8_L001_R1_alignedsorted.bam`

When I say the home directory, I am referring to the directory (any folder) where you keep raw_sequences, scripts and environment folders at the beginning, which is "RNA-data-analyzer" in your case.

**Comment by sekhwal** [comment] 2020-08-03 17:41
Hi,
The pipeline showing the same error while running the final "python run.py" command.

it seems conda is installed properly. Please take a look in commands:

(dataanalyzer) [ravibioinfo@gmatuic RNA-data-analyzer]$ conda update conda

PackageNotInstalledError: Package is not installed in prefix.
  prefix: /home/ravibioinfo/miniconda3/envs/dataanalyzer
  package name: conda

(dataanalyzer) [ravibioinfo@gmatuic RNA-data-analyzer]$ which conda
~/miniconda3/condabin/conda
(dataanalyzer) [ravibioinfo@gmatuic RNA-data-analyzer]$ conda --version
conda 4.8.3
(dataanalyzer) [ravibioinfo@gmatuic RNA-data-analyzer]$

**Comment by jkkbuddika** [comment] 2020-08-03 17:54
Hi,
Here's what I would do. Run following commands.

conda remove --name dataanalyzer --all [This command removes the dataanalyzer conda environment]
conda create -n dataanalyzer -c conda-forge -c bioconda python=3.7 [This command remakes the dataanalyzer environment]
conda install -n dataanalyzer -c conda-forge -c bioconda fastqc star qualimap samtools deeptools subread multiqc pandas [This command installs all required packages to run the pipeline]

Essentially, all required packages must be installed properly to run the pipeline (see [Step 2](https://github.com/jkkbuddika/RNA-Seq-Data-Analyzer/blob/master/USERGUIDE.md#step-2-setup-the-miniconda-environment) of the User Guide).

Let me know if you run into more issues.

**Comment by sekhwal** [comment] 2020-08-03 19:07
Hi, I have already tried removing environment and re-generated. However, I will do it once again and let you know if it works.

**Comment by sekhwal** [comment] 2020-08-03 19:40
---Let me remove miniconda3 and re-install it. I am following these commands:

(base) [ravibioinfo@gmatuic ~]$ python --version
Python 3.8.3
(base) [ravibioinfo@gmatuic ~]$ cd /home/ravibioinfo/
(base) [ravibioinfo@gmatuic ~]$ bash Miniconda3-latest-Linux-x86_64.sh 
(base) [ravibioinfo@gmatuic ~]$ conda activate
(base) [ravibioinfo@gmatuic ~]$ which conda
~/anaconda3/bin/conda
(base) [ravibioinfo@gmatuic ~]$ conda --version
conda 4.8.3
(base) [ravibioinfo@gmatuic ~]$ 

---Now I can see miniconda3 folder in my home directory (/home/ravibioinfo/miniconda3):

Could you please let me know how to add conda to path and activate it? I just want to make sure there are no packages left.

**Comment by sekhwal** [comment] 2020-08-03 19:48
Once I give the following command it is showing ERROR. Could you let me know, do I need to add path of miniconda before running this command?

(base) [ravibioinfo@gmatuic environment]$ conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - ld_impl_linux-64==2.34=h53a641e_0
  - binutils_impl_linux-64==2.34=h53a641e_0

**Comment by jkkbuddika** [comment] 2020-08-03 19:58
Can you try running these commands instead?

conda create -n dataanalyzer -c conda-forge -c bioconda python=3.7
conda install -n dataanalyzer -c conda-forge -c bioconda fastqc star qualimap samtools deeptools subread multiqc pandas

**Comment by sekhwal** [comment] 2020-08-03 20:04
I tried. However, they are not able to make dataanalyzer environment in
miniconda3/env directory. I think I need to RUN following commands and set
path of miniconda before proceeding these commands.

cd environment

conda env create -f environment.yml

*----*
*Manoj Kumar*

**Comment by jkkbuddika** [comment] 2020-08-03 20:07
Here is a nice article that explains how to add miniconda to PATH variable. See the commands you have to run. 

https://developers.google.com/earth-engine/python_install-conda

Adding miniconda to PATH variable has to be done.

**Comment by sekhwal** [comment] 2020-08-03 21:23
Hi, it seems everything is installed. However, it is still showing the same ERROR of samtools. Are you able to RUN successfully at your hand?
Do you think, should I use python version 3.8.3 that I have instead of 3.7 in the following command?

conda create -n dataanalyzer -c conda-forge -c bioconda python=3.7

**Comment by sekhwal** [comment] 2020-08-04 15:56
Hi, Is your pipeline works for a very large number of files. I have big
size 180 RNASeq samples fastq parirend reads files.

**Comment by jkkbuddika** [comment] 2020-08-04 16:32
Hi, I don't think the problem is coming from the Python version. Sorry, I didn't have much time to look at the error carefully. By doing a Google search I think I found the fix (see this [thread](https://github.com/bioconda/bioconda-recipes/issues/12100)).

Try running this command:
`conda install -n dataanalyzer -c bioconda samtools openssl=1.0`

Hopefully this will fix the Samtools error you were having. YES, I managed to run the whole pipeline without having any issues. The pipeline should be able to handle any number as long as you have sufficient memory and all input files are properly named.

Let me know whether you got the error fixed by running above.

**Comment by sekhwal** [comment] 2020-08-04 16:47
it is showing the following message while installing. However, it seems
packages are installed. Let me try running the pipeline once again.

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with
flexible solve.
Solving environment: failed with repodata from current_repodata.json, will
retry with next repodata source.
Collecting package metadata (repodata.json): done

**Comment by sekhwal** [comment] 2020-08-04 18:43
Hi,

It is done without the ERROR! Now, which file should I take for differential
gene expression analysis using R package DESeq2
<https://bioconductor.org/packages/release/bioc/html/DESeq2.html> ?

Here is the pipeline successfully completing message!

Generating MultiQC Reports for star_genome ...

[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   :
/home/ravibioinfo/RNA-data-analyzer/star_genome
Searching 16 files..  [####################################]  100%
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

Running MultiQC done!!!


Data analysis is successfully completed !!!

**Comment by jkkbuddika** [comment] 2020-08-04 18:57
Awesome! 👏 

The pipeline quantifies both reads mapped genes and exons (no intronic reads). You will find them in folders `featureCounts_gene` and `featureCounts_exon`. I usually use exon counts for my DESeq2 analyses. Open that folder and you will see a file named `exon_DESeq2_Input.txt` and that is the input for DESeq2.

But before doing this take a look at html reports inside the `MultiQC_Summary` folder. Particularly `star_aligned_MultiQC_Report.html`. See whether the alignment rate is good (you would expect to see high % of uniquely mapped reads).

**Comment by sekhwal** [comment] 2020-08-04 19:18
I just tried with one sample fastq files. The alignment score showing 9.8%
in star_aligned_multiQC_Report.html file (file attached). However, I will
marge some other fastq files of this sample and try with some more samples.
Let me try if the pipeline works for large dataset.

Do you think kallisto <https://pachterlab.github.io/kallisto/starting> is
better than STAR as I was recommended in my original query section at
BIOSTAR to use this since I have a very large dataset? I think Kallisto
needs transcriptome file to generate index file.

Thank you!

Manoj

**Comment by jkkbuddika** [comment] 2020-08-04 19:31
Try and see. I don't see why it should not work given you have set up the conda environment perfectly now. But, it surely will take a long time to run all (you said you have 180 ish?). At the end, the final `featureCounts_gene` or `featureCounts_exon` will have 180 columns corresponding to each of your dataset with raw counts which you can directly import to DESeq2 for differential gene expression analysis.

Honestly, I haven't used Kallisto. You can try and see.

**Comment by sekhwal** [comment] 2020-08-04 19:54
Sounds good!
I have one more question, how the pipeline defines the length of good and
low quality while using CutAdapt since it is automatically.
Does it remove the length which is low quality automatically? is that
correct?

**Comment by jkkbuddika** [comment] 2020-08-04 21:09
I have set the `-quality-cutoff 5` as the quality trimming setting. That is the quality trimming the pipeline does by default.

**Comment by sekhwal** [comment] 2020-08-06 15:01
Hi, When I RUN the pipeline again, it generated the same samtools ERROR again.
Do I have to RUN the following command every time before RUN the pipeline?

$conda install -n dataanalyzer -c bioconda samtools openssl=1.0


ERROR:-----

Alignment Quality Assessment Completed!!!

Filtering and Sorting: 2020_270_R1_aligned.bam ...

[bam_sort_core] merging from 8 files and 8 in-memory blocks...

Indexing: 2020_270_R1_alignedsorted.bam ...

[E::hts_idx_push] Chromosome blocks not continuous
samtools index: failed to create index for "/DataAnalysis/Manoj-data/RNA-Seq-Data-Analyzer/sam_sorted/2020_270_R1_alignedsorted.bam"
Traceback (most recent call last):
  File "run.py", line 41, in <module>
    ss.sam_sorting()
  File "/DataAnalysis/Manoj-data/RNA-Seq-Data-Analyzer/scripts/SamTools.py", line 61, in sam_sorting
    sp.check_call(command, shell=True)
  File "/home/ravibioinfo/miniconda3/envs/dataanalyzer/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'samtools index /DataAnalysis/Manoj-data/RNA-Seq-Data-Analyzer/sam_sorted/2020_270_R1_alignedsorted.bam' returned non-zero exit status 1.

**Comment by jkkbuddika** [comment] 2020-08-07 14:37
You don't have to. Samtools seems to work just fine. The error says there is a problem with the sorting. Are you running the pipeline with deduplication TRUE or FALSE?

**Comment by sekhwal** [comment] 2020-08-07 15:40
Hi,
Last time I did deduplication FALSE, then it showed the ERROR. However, I
re-run the pipeline again with deduplication TRUE and now it finished
without the ERROR. Actually, I have not idea about the deduplication option.

**Comment by sekhwal** [comment] 2020-08-07 15:51
One more thing, I RUN the pipeline with six samples. In its output featureCount file (exon_DESeq2_Input.txt), is it showing all samples results? The first column is the genes. Right? Others there are seven more columns. However, I have six samples.

Here is some line of the featureCount file (exon_DESeq2_Input.txt). 

Geneid	Length	/DataAnalysis/data/RNA-Seq-Data-Analyzer/sam_sorted/2020_270_R1_alignedsorted.bam	/DataAnalysis/data/RNA-Seq-Data-Analyzer/sam_sorted/2020_272_R1_alignedsorted.bam	/DataAnalysis/data/RNA-Seq-Data-Analyzer/sam_sorted/2020_274_R1_alignedsorted.bam	/DataAnalysis/data/RNA-Seq-Data-Analyzer/sam_sorted/2020_278_C_R1_alignedsorted.bam	/DataAnalysis/data/RNA-Seq-Data-Analyzer/sam_sorted/2020_282_C_R1_alignedsorted.bam	/DataAnalysis/data/RNA-Seq-Data-Analyzer/sam_sorted/2020_284_C_R1_alignedsorted.bam
DDX11L1	2541	0	0	0	0	0	0
WASH7P	       15167	0	0	1	0	4	1
MIR6859-1	68	        0	0	0	0	0	0
MIR1302-2HG	1556	0	0	0	0	0	0

**Comment by jkkbuddika** [comment] 2020-08-07 18:07
That is correct. Each column here represent counts from each sample. I use Samtools to remove potential PCR duplicates, however, this is optional. Let me revisit the problem with deduplication FALSE giving the error.

**Comment by sekhwal** [comment] 2020-08-07 18:59
Hi,
It would be great if you could suggest some initial steps and commands of
DESeq2. I am lost in its manual. I am not getting where to start it to
process the differential gene expression using DeSeq2.
Thank you,

**Comment by jkkbuddika** [comment] 2020-08-09 01:33
Hi, Sure. I am not exactly sure what you want to do. But, here are some steps. I usually like to rename column names of your samples. I don't like having long column names (like /DataAnalysis/data/RNA-Seq-Data-Analyzer/sam_sorted/2020_270_R1_alignedsorted.bam). Many options, you can do this easily by opening the txt file on excel (make them short like 2020_270 for instance). Or you can rename columns using R as well. Let's say you manually edited column names, once you are done with that do following things. Let's say 270, 272, and 274 above represent "Control" and 278, 282, 284 represent "Mutant" and you want to do Mutant vs Control comparison. You can do this by using a R script something like this:

```

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("DESeq2")

library DESeq2
countdata <- read.delim("/path/to/exon_DESeq2_Input.txt", header=TRUE)
colnames(countdata)
countdata <- countdata[, c(2:7)]
colnames(countdata)
countdata <- as.matrix(countdata)
colnames(countdata)
(genotype <- factor(c(rep("Control", 3), rep("Mutant", 3))))
(coldata <- data.frame(row.names=colnames(countdata), genotype))
dds <- DESeqDataSetFromMatrix(countData=countdata, colData=coldata, design=~genotype)
dds <- DESeq(dds)
resultsNames(dds)
res <- results(dds, contrast = c("genotype", "Mutant", "Control"))
res <- res[order(res$padj), ]
head(res)
```
Hope this will help.

**Comment by sekhwal** [comment] 2020-08-11 17:51
Hi, I tried the pipeline with 6 samples. However, alignment % is still low. Is any way to improve the percentage.
![pic1](https://user-images.githubusercontent.com/26156590/89931079-56da0d00-dbd1-11ea-99f6-e9e39291de51.png)

**Comment by jkkbuddika** [comment] 2020-08-11 19:39
Have you tried kallisto? What is the alignment rate there?

**Comment by sekhwal** [comment] 2020-08-11 19:52
Yes! I tried kallisto with the same 6 samples and got the result files.
However, I am not sure where is the alignment rate. It
produces abundance.h5, abundance.tsv and run_info.json in its result files.

Manoj
*----*

**Comment by sekhwal** [comment] 2020-08-13 19:18
Hi,
Do you think if I change some parameter of Cutadapt, I can get a better alignment rate?

**Comment by jkkbuddika** [comment] 2020-08-15 20:46
Hi, Take a look at FastQC results of your samples. See whether you find any high level of adapter contamination. If you find this is true you might have to trim adapter sequences. Having adapter contamination can cause problems in mapping.

**Comment by sekhwal** [comment] 2020-08-17 15:11
Hi, 
Let me describe my data structure. I have got four files (fastq) of a sample and merged using $cat command and I RUN fastqc for all five samples. 
Here are the MultiQC results of five samples. I am not sure where I can see the adapter contamination information. Could you indicate?
![pic1](https://user-images.githubusercontent.com/26156590/90441157-14677300-e09e-11ea-93b4-4c43673ef1cc.png)

**Comment by sekhwal** [comment] 2020-08-18 16:55
I used TrimGalore with the following script to remove adaptors. TrimGalore improves the quality with option -q 20 automatically. Do I need to RUN your pipeline with the same Cutadapt parameters?
![pic1](https://user-images.githubusercontent.com/26156590/90563276-2cf08f80-e169-11ea-8d01-075621891ed4.png)



#!/bin/bash 
for f1 in *_R1.fastq.gz 
do
        f2=${f1%%_R1.fastq.gz}"_R2.fastq.gz"
        trim_galore --illumina --paired --fastqc -o /DataAnalysis/Manoj-data/fastqc-analysis/control/ $f1 $f2 
done

**Comment by jkkbuddika** [comment] 2020-08-19 18:32
Hi, Sorry for the late response. Yes, run the pipeline as it is and see. If you still have problems let me change some parameters and send a custom script for you. Hopefully, given the FastQC looks better now, you should get improved results.

**Comment by sekhwal** [comment] 2020-08-20 14:44
Yup! I tried. However, the pipeline has stuck at the following step for the whole night. I will try again.


Quantifying genes ...

Reading data from <STDIN> for featureCounts ...

**Comment by jkkbuddika** [comment] 2020-08-20 16:50
Check all the intermediate folders. If this happens that could mean that an intermediate step had been passed without having an error. I would go back and see if the star_aligned or sam_sorted folders are empty.

**Comment by sekhwal** [comment] 2020-08-21 14:54
I just RUN the pipeline with two control and two mutant samples. However, the pipeline has been stuck at the same step for overnight. Yes, star_aligned and sam_sorted folders are empty. Do you think it is because I used trim_galore to improve the seqs.

-----
Alignment Quality Assessment Completed!!!
Filtering, Sorting and Indexing Completed!!!
BigWig files were deposited!!!
Feature counting started ...

Quantifying genes ...

Reading data from <STDIN> for featureCounts ...

**Comment by sekhwal** [comment] 2020-08-21 15:08
Here are the samples data.
![pic1](https://user-images.githubusercontent.com/26156590/90905740-39a5fb00-e396-11ea-8fd4-0ba1bc74df4c.png)

**Comment by jkkbuddika** [comment] 2020-08-21 16:16
I see. The problem is the file name. Please **rename** file extension from **.fq** to **.fastq** and re-run. I should probably fix this in the next release to allow both .fq to .fastq extensions on input sequences.

**Comment by sekhwal** [comment] 2020-08-21 16:36
So, just rename will work from .fq to .fastq??

**Comment by jkkbuddika** [comment] 2020-08-21 16:46
Yes! It must work!

**Comment by sekhwal** [comment] 2020-08-24 14:56
Hi, Yes, It worked. However, it seems the similarity score is still low.
Please see the attachment of star_aligned_MultiQC_Report. Do you think, I
need to change some parameters to get high similarity score.

Manoj

**Comment by jkkbuddika** [comment] 2020-08-24 17:19
Could you rerun the pipeline with Run Mode option set to 0 (single-end, only R1 read will be used for analysis).

Also, I don't see the star_aligned_MultiQC_Report.

**Comment by sekhwal** [comment] 2020-08-24 17:31
Here is the star_aligned_MultiQC_Report. Please let me know if you are not
able to open it.

**Comment by jkkbuddika** [comment] 2020-08-25 00:41
Can you email it to me? I can't find the file.

**Comment by sekhwal** [comment] 2020-08-25 15:10
Hi, I am attaching a zip file of star_aligned_MultiQC_Report. Please see
the attachment. If still, you are not able to find .zip, I am also
attaching an image of star_aligned_MultiQC_Report.

I also RUN the pipeline with Run Mode option set to 0 (single-end, only R1
read will be used for analysis). (star_aligned_MultiQC_Report. is pic 2).
Can you assess the results?

Manoj

**Comment by jkkbuddika** [comment] 2020-08-25 15:24
Hi, Attach them in a separate email and send them. I don't see them.

**Comment by jkkbuddika** [comment] 2020-09-03 14:09
> That is correct. Each column here represent counts from each sample. I use Samtools to remove potential PCR duplicates, however, this is optional. Let me revisit the problem with deduplication FALSE giving the error.

The Deduplication FALSE error problem is resolved.

**Comment by jkkbuddika** [comment] 2020-09-03 14:15
> That is correct. Each column here represent counts from each sample. I use Samtools to remove potential PCR duplicates, however, this is optional. Let me revisit the problem with deduplication FALSE giving the error.

The Deduplication FALSE error has been resolved!!!

**Closed as completed** 2020-09-17 15:25 UTC
